---

- name: Install Postfix Deamon
  apt:
    name: postfix
    state: installed

- name: Install Postfix Deamon
  apt:
    name: "{{ package_to_install }}"
    update_cache: "{{ update_apt_cache }}"
    state: latest
  with_items:
    - postfix
  loop_control:
    loop_var: package_to_install

- name: Start Postfix
  service:
    name: "{{ postfix__server_service }}"
    state: started
    enabled: "{{ postfix__enabled_on_startup }}"
