---

- name: Load OS-Specific Tasks
  include: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution|lower }}.yml"
   - "os-{{ ansible_os_family|lower }}.yml"
   - "os-default.yml"

- name: Copy the my.cnf config file
  template:
    src=my.cnf.j2
    dest={{ mysql__my_cnf_path }}my.cnf

- name: Ensure MySQL is started and enabled on boot.
  service: name=mysql state=started enabled={{ mysql__enabled_on_startup }}
  register: mysql_service_configuration

- name: Install the Python MySQLB module
  pip: name=mysqlclient

- name: Create MySQL App database
  mysql_db: name={{mysql__db_name}} state=present

- name: Create MySQL App user
  mysql_user:
    name={{mysql__db_user}}
    host=localhost
    password={{mysql__db_password}}
    priv=*.*:ALL
    state=present
