---

mysql__enabled_on_startup: "yes"
mysql__db_user: "{{db_user}}"
mysql__db_password: "{{db_password}}"
mysql__db_name: "{{db_name}}"
mysql__port: 3306
mysql__bind_address: "127.0.0.1"
mysql__my_cnf_path: "/etc/mysql/"
mysql__socket_dir: "/var/run/mysqld/mysqld.sock"
mysql__log_dir: "/var/log/mysql/error.log"
mysql__data_dir: "/var/lib/mysql"
